
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 07 18:35:49 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 45;
  public static final int CONST = 4;
  public static final int CHAR = 21;
  public static final int EQUALS = 28;
  public static final int PERIOD = 41;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 9;
  public static final int FOR = 12;
  public static final int MINUS = 24;
  public static final int GREATER_THAN = 30;
  public static final int SEMICOLON = 39;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int LEFT_BRACE = 42;
  public static final int COMMA = 40;
  public static final int BOOL = 22;
  public static final int CLASS = 5;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int RIGHT_PARENTHESIS = 47;
  public static final int PLUS = 23;
  public static final int ASSIGN = 36;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int RIGHT_BRACE = 43;
  public static final int NUMBER = 20;
  public static final int MOD = 27;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 17;
  public static final int ELSE = 11;
  public static final int ENUM = 8;
  public static final int READ = 15;
  public static final int NOT_EQUALS = 29;
  public static final int EXTENDS = 6;
  public static final int DEC = 38;
  public static final int GREATER_THAN_EQUALS = 31;
  public static final int LESS_THAN = 32;
  public static final int LESS_THAN_EQUALS = 33;
  public static final int IMPLEMENTS = 7;
  public static final int LEFT_BRACKET = 44;
  public static final int LEFT_PARENTHESIS = 46;
  public static final int PRINT = 14;
}

